// This is a part of the Active Template Library. 
// Copyright (c) Microsoft Corporation.  All rights reserved.
//
// This source code is only intended as a supplement to the
// Active Template Library Reference and related
// electronic documentation provided with the library.
// See these sources for detailed information regarding the
// Active Template Library product.

// ATLEventHandling.idl : IDL source for ATLEventHandling.dll
//

// This file will be processed by the MIDL tool to
// produce the type library (ATLEventHandling.tlb) and marshalling code.

import "oaidl.idl";
import "ocidl.idl";

   [
      object,
      uuid(BC7648FD-B55E-11D2-BA67-00C04F8EC847),
      dual,
      helpstring("ISwitch Interface"),
      pointer_default(unique)
   ]
   interface ISwitch : IDispatch
   {
      [id(1), helpstring("method Start")] HRESULT Start();
      [id(2), helpstring("method Stop")] HRESULT Stop();
   };

[
   uuid(BC7648EF-B55E-11D2-BA67-00C04F8EC847),
   version(1.0),
   helpstring("ATLEventHandling 1.0 Type Library")
]
library ATLEVENTHANDLINGLib
{
   importlib("stdole32.tlb");
   importlib("stdole2.tlb");

   [
      uuid(BC7648FC-B55E-11D2-BA67-00C04F8EC847),
      helpstring("Simple Class")
   ]
   coclass Simple
   {
      [default] interface ISwitch;
   };
   [
      uuid(BC7648FE-B55E-11D2-BA67-00C04F8EC847),
      helpstring("NotSoSimple Class")
   ]
   coclass NotSoSimple
   {
      [default] interface ISwitch;
   };
};
