// NVC_MFC_AxFont.idl : type library source for ActiveX Control project.

// This file will be processed by the MIDL compiler tool to
// produce the type library (NVC_MFC_AxFont.tlb) that will become a resource in
// NVC_MFC_AxFont.ocx.

#include <olectl.h>
#include <idispids.h>

[ uuid(B200302C-C816-425F-8FDF-EFBA05298CA0), version(1.0),
  helpfile("NVC_MFC_AxFont.hlp"),
  helpstring("NVC_MFC_AxFont ActiveX Control module"),
  control ]
library NVC_MFC_AxFontLib
{
	importlib(STDOLE_TLB);

	//  Primary dispatch interface for CMyAxFontCtrl

	[ uuid(350BC14F-5FCB-4C5F-B6C6-F79FB8624593),
	  helpstring("Dispatch interface for MyAxFont Control")]
	dispinterface _DNVC_MFC_AxFont
	{
		properties:
// <Snippet2>
         [id(DISPID_FONT)] IFontDisp*Font;
// </Snippet2>
         [id(DISPID_CAPTION), helpstring("property Caption")] BSTR Caption;
// <Snippet7>
         [id(1)] IDispatch* HeadingFont;
// </Snippet7>
   methods:
	};

	//  Event dispatch interface for CMyAxFontCtrl

	[ uuid(E03AC13E-ECD9-425C-B681-D0DDBCBCBB31),
	  helpstring("Event interface for MyAxFont Control") ]
	dispinterface _DNVC_MFC_AxFontEvents
	{
		properties:
			//  Event interface has no properties

		methods:
	};

	//  Class information for CMyAxFontCtrl

	[ uuid(565A9384-83EC-4FA1-BA06-BEFE2FC35E7C),
	  helpstring("MyAxFont Control"), control ]
	coclass NVC_MFC_AxFont
	{
		[default] dispinterface _DNVC_MFC_AxFont;
		[default, source] dispinterface _DNVC_MFC_AxFontEvents;
	};

};
