// NVC_OLEDB_Provider.idl : IDL source for NVC_OLEDB_Provider
//

// This file will be processed by the MIDL tool to
// produce the type library (NVC_OLEDB_Provider.tlb) and marshalling code.

import "oaidl.idl";
import "ocidl.idl";

[
	uuid(0D1A3F34-CF81-4D76-9DAD-93E8BA458338),
	version(1.0),
	helpstring("NVC_OLEDB_Provider 1.0 Type Library")
]
library NVC_OLEDB_ProviderLib
{
	importlib("stdole2.tlb");
	[
		uuid(3A9DC39D-C736-408F-9769-AEC77A84C7F5),
		helpstring("MyProvider Class")
	]
	coclass MyProvider
	{
		interface IUnknown;
	};
};
