        [eventadd]
        HRESULT PrimeNumberFound(
            [in] PrimeNumberEvent* eventHandler, 
            [out, retval] EventRegistrationToken* eventCookie);
        [eventremove] 
        HRESULT PrimeNumberFound(
            [in] EventRegistrationToken eventCookie);