//{{NO_DEPENDENCIES}}
// Microsoft Visual C++ generated include file.
// Used by NVC_MFC_CTreeCtrl.RC
//
#define IDR_MAINFRAME					128
#define IDD_NVC_MFC_CTREECTRL_DIALOG				102
#define IDC_BUTTON1					103
#define IDR_TREEMENU                    182
#define ID_MYTREE                       124
#define IDB_UP                          156
#define IDB_DOWN                        158
#define ID_TREECTRL_CREATEDRAGIMAGE     32799
#define ID_TREECTRL_DELETEALLITEMS      32800
#define ID_TREECTRL_DELETEITEM          32801
#define ID_TREECTRL_EDITLABEL           32802
#define ID_TREECTRL_ENSUREVISIBLE       32803
#define ID_TREECTRL_GETCHILDITEM        32804
#define ID_TREECTRL_GETCOUNT            32805
#define ID_TREECTRL_GETDROPHIGHLIGHTITEM 32806
#define ID_TREECTRL_GETEDITCONTROL      32807
#define ID_TREECTRL_GETIMAGELIST        32808
#define ID_TREECTRL_GETINDENT           32809
#define ID_TREECTRL_GETINSERTMARKCOLOR  32810
#define ID_TREECTRL_GETITEMDATA         32811
#define ID_TREECTRL_GETITEMHEIGHT       32812
#define ID_TREECTRL_GETITEMIMAGE        32813
#define ID_TREECTRL_GETITEMRECT         32814
#define ID_TREECTRL_GETITEMSTATE        32815
#define ID_TREECTRL_GETLINECOLOR        32816
#define ID_TREECTRL_GETNEXTITEM         32817
#define ID_TREECTRL_GETNEXTSIBLINGITEM  32818
#define ID_TREECTRL_GETPREVSIBLINGITEM  32819
#define ID_CHUNK2_GETPREVVISIBLEITEM    32820
#define ID_CHUNK2_GETSELECTEDITEM       32821
#define ID_CHUNK2_GETTOOLTIPS           32822
#define ID_CHUNK2_HITTEST               32823
#define ID_CHUNK2_SELECTSETFIRSTVISIBLE 32824
#define ID_CHUNK2_SETCHECK              32825
#define ID_CHUNK2_SETINSERTMARK         32826
#define ID_CHUNK2_SETITEM               32827
#define ID_CHUNK2_SETITEMDATA           32828
#define ID_CHUNK2_SETITEMTEXT           32829
#define ID_CHUNK2_SETLINECOLOR          32830
#define ID_CHUNK2_SETTEXTCOLOR          32831
#define ID_CHUNK2_SORTCHILDREN          32832
#define ID_CHUNK2_SORTCHILDRENCB        32833

// Next default values for new objects
// 
#ifdef APSTUDIO_INVOKED
#ifndef APSTUDIO_READONLY_SYMBOLS

#define _APS_NEXT_RESOURCE_VALUE	129
#define _APS_NEXT_CONTROL_VALUE		1000
#define _APS_NEXT_SYMED_VALUE		101
#define _APS_NEXT_COMMAND_VALUE		32771
#endif
#endif
