#pragma once

template <class T>
class CProxy_IConnect1Events : public IConnectionPointImpl<T, &__uuidof( _IConnect1Events ), CComDynamicUnkArray>
{
   //Warning this class will  be regenerated by the wizard.
public:
};
