#pragma once

template <class T>
class CProxy_IConnect2Events : public IConnectionPointImpl<T, &__uuidof( _IConnect2Events ), CComDynamicUnkArray>
{
   //Warning this class will  be regenerated by the wizard.
public:
};
