// NVC_ATL_Windowing.idl : IDL source for NVC_ATL_Windowing
//

// This file will be processed by the MIDL tool to
// produce the type library (NVC_ATL_Windowing.tlb) and marshalling code.

#include "olectl.h"
#include "olectl.h"
import "oaidl.idl";
import "ocidl.idl";

[
   object,
   uuid(33D0EA3E-AD8B-4950-B58F-1EE00107D7D4),
   dual,
   nonextensible,
   helpstring("IMyCtrl Interface"),
   pointer_default(unique)
]
interface IMyCtrl : IDispatch{
   [id(1), helpstring("method CWindowAttach")] HRESULT CWindowAttach(void);
   [id(2), helpstring("method CWindowBringWindowToTop")] HRESULT CWindowBringWindowToTop(void);
   [id(3), helpstring("method CWindowCenterWindow")] HRESULT CWindowCenterWindow(void);
   [id(4), helpstring("method CWindowDestroyWindow")] HRESULT CWindowDestroyWindow(void);
   [id(5), helpstring("method CWindowDetach")] HRESULT CWindowDetach(void);
   [id(6), helpstring("method CWindowEnableWindow")] HRESULT CWindowEnableWindow(void);
   [id(7), helpstring("method CWindowGetClientRect")] HRESULT CWindowGetClientRect(void);
   [id(8), helpstring("method CWindowGetDC")] HRESULT CWindowGetDC(void);
   [id(9), helpstring("method CWindowGetExStyle")] HRESULT CWindowGetExStyle(void);
   [id(10), helpstring("method CWindowGetParent")] HRESULT CWindowGetParent(void);
   [id(11), helpstring("method CWindowGetStyle")] HRESULT CWindowGetStyle(void);
   [id(12), helpstring("method CWindowGetTopWindow")] HRESULT CWindowGetTopWindow(void);
   [id(13), helpstring("method CWindowGetWindowDC")] HRESULT CWindowGetWindowDC(void);
   [id(14), helpstring("method CWindowGetWindowProcessID")] HRESULT CWindowGetWindowProcessID(void);
   [id(15), helpstring("method CWindowGetWindowThreadID")] HRESULT CWindowGetWindowThreadID(void);
   [id(16), helpstring("method CWindowHideCaret")] HRESULT CWindowHideCaret(void);
   [id(17), helpstring("method CWindowInvalidate")] HRESULT CWindowInvalidate(void);
   [id(18), helpstring("method CWindowIsIconic")] HRESULT CWindowIsIconic(void);
   [id(19), helpstring("method CWindowIsWindow")] HRESULT CWindowIsWindow(void);
   [id(20), helpstring("method CWindowIsWindowEnabled")] HRESULT CWindowIsWindowEnabled(void);
   [id(21), helpstring("method CWindowIsWindowVisible")] HRESULT CWindowIsWindowVisible(void);
   [id(22), helpstring("method CWindowIsWindowUnicode")] HRESULT CWindowIsWindowUnicode(void);
   [id(23), helpstring("method CWindowMessageBox")] HRESULT CWindowMessageBox(void);
   [id(24), helpstring("method CWindowModifyStyle")] HRESULT CWindowModifyStyle(void);
   [id(25), helpstring("method CWindowModifyStyleEx")] HRESULT CWindowModifyStyleEx(void);
   [id(26), helpstring("method CWindowPostMessage")] HRESULT CWindowPostMessage(void);
   [id(27), helpstring("method CWindowRedrawWindow")] HRESULT CWindowRedrawWindow(void);
   [id(28), helpstring("method CWindowSendMessage")] HRESULT CWindowSendMessage(void);
   [id(29), helpstring("method CWindowSetActiveWindow")] HRESULT CWindowSetActiveWindow(void);
   [id(30), helpstring("method CWindowSetFocus")] HRESULT CWindowSetFocus(void);
   [id(31), helpstring("method CWindowSetParent")] HRESULT CWindowSetParent(void);
   [id(32), helpstring("method CWindowSetRedraw")] HRESULT CWindowSetRedraw(void);
   [id(33), helpstring("method CWindowSetText")] HRESULT CWindowSetText(void);
   [id(34), helpstring("method CWindowShowCaret")] HRESULT CWindowShowCaret(void);
   [id(35), helpstring("method CWindowShowWindow")] HRESULT CWindowShowWindow(void);
   [id(36), helpstring("method CWindowUpdateWindow")] HRESULT CWindowUpdateWindow(void);
   [id(37), helpstring("method CAxWindowCreateControl")] HRESULT CAxWindowCreateControl(void);
   [id(38), helpstring("method TestCustomWndDlg")] HRESULT TestCustomWndDlg(void);
   [id(39), helpstring("method CreateCAxWindow")] HRESULT CreateCAxWindow(void);
   [id(40), helpstring("method TestMyChainedWnd")] HRESULT TestMyChainedWnd(void);
   [id(41), helpstring("method TestMyComponent")] HRESULT TestMyComponent(void);
   [id(42), helpstring("method TestEasySink")] HRESULT TestEasySink(void);
   [id(43), helpstring("method ToggleIntQITimer")] HRESULT ToggleIntQITimer([in] BOOL bStart);
   [id(44), helpstring("method TestMyClass")] HRESULT TestMyClass(void);
   [id(45), helpstring("method TestpAtlModule")] HRESULT TestpAtlModule(void);
};

[
   object,
   uuid(D6968477-D60B-47CE-830C-44A4D591986A),
   dual,
   nonextensible,
   helpstring("IAtlEdit Interface"),
   pointer_default(unique)
]
interface IAtlEdit : IDispatch{
};

[
   object,
   uuid(232BC896-D2C5-41AD-8E77-69C924223A97),
   dual,
   nonextensible,
   helpstring("IMyWindow Interface"),
   pointer_default(unique)
]
interface IMyWindow : IDispatch{
};

[
   object,
   uuid(07536329-0075-4EE7-BB40-F250F57F446D),
   dual,
   nonextensible,
   helpstring("IPolyCtl Interface"),
   pointer_default(unique)
]
interface IPolyCtl : IDispatch{
   [propput, bindable, requestedit, id(DISPID_FILLCOLOR)]
   HRESULT FillColor([in]OLE_COLOR clr);
   [propget, bindable, requestedit, id(DISPID_FILLCOLOR)]
   HRESULT FillColor([out, retval]OLE_COLOR* pclr);
   [propget, id(1), helpstring("property Sides")] HRESULT Sides([out, retval] short* pVal);
   [propput, id(1), helpstring("property Sides")] HRESULT Sides([in] short newVal);
};

[
   object,
   uuid(B2A8532F-F0A8-4BC4-814C-69240C607E96),
   dual,
   nonextensible,
   helpstring("IMyCustomWnd Interface"),
   pointer_default(unique)
]
interface IMyCustomWnd : IDispatch{
};

[
   object,
   uuid(45C8B4DA-69C8-4E2A-9B80-2BDB337994A4),
   dual,
   nonextensible,
   helpstring("IHelper Interface"),
   pointer_default(unique)
]
interface IHelper : IDispatch{
   [id(1), helpstring("method ShowPage")] HRESULT ShowPage([in] BSTR bstrCaption, [in] BSTR bstrID, [in] IUnknown* pUnk);
};
[
   object,
   uuid(DF5F3165-C8F9-4284-AEB3-A7B0A191B266),
   dual,
   nonextensible,
   helpstring("IBuddy Interface"),
   pointer_default(unique)
]
interface IBuddy : IDispatch{
   [id(1), helpstring("method DoSomething")] HRESULT DoSomething(void);
};

[
   object,
   uuid(10E1DE96-839A-414A-9276-1C7643CAF116),
   dual,
   nonextensible,
   helpstring("IMyDispEventClass Interface"),
   pointer_default(unique)
]
interface IMyDispEventClass : IDispatch{
};
[
   object,
   uuid(84CE6746-5831-4B27-96C4-2908C2FF12D5),
   helpstring("IConnect1 Interface"),
   pointer_default(unique)
]
interface IConnect1 : IUnknown{
};
[
   object,
   uuid(F5867638-D005-43E4-8749-F19DDEDBC7E5),
   helpstring("IConnect2 Interface"),
   pointer_default(unique)
]
interface IConnect2 : IUnknown{
};
[
   object,
   uuid(8ADE7694-2E4D-4D34-840D-39A732D1702C),
   dual,
   nonextensible,
   helpstring("IATLAsync Interface"),
   pointer_default(unique)
]
interface IATLAsync : IDispatch{
   [propget, id(1), helpstring("property URL")] HRESULT URL([out, retval] BSTR* pVal);
   [propput, id(1), helpstring("property URL")] HRESULT URL([in] BSTR newVal);
};

[
   object,
   uuid(BEC0B77B-772E-4592-91B7-743E69ED039F),
   dual,
   nonextensible,
   helpstring("IMyComponent Interface"),
   pointer_default(unique)
]
interface IMyComponent : IDispatch{
   [id(1), helpstring("method ShowMsg")] HRESULT ShowMsg([in] BSTR bstrMsg);
};
[
   object,
   uuid(B0E38076-7E7F-4D09-AE5E-E0A199BEF8D0),
   dual,
   nonextensible,
   helpstring("IMySink Interface"),
   pointer_default(unique)
]
interface IMySink : IDispatch{
};
[
   uuid(8F2D074E-BAE0-4670-BC04-B3A92FC3B435),
   helpstring("_IMyComponentEvents Interface")
]
interface _IMyComponentEvents : IUnknown
{
   [helpstring("method ShowMyMsg")] HRESULT ShowMyMsg([in] BSTR bstrMsg);
};
[
   object,
   uuid(C83E7E64-1145-414B-BD7A-0FDCCEFAD8F2),
   dual,
   nonextensible,
   helpstring("ICBuddySink Interface"),
   pointer_default(unique)
]
interface ICBuddySink : IDispatch{
};
[
   object,
   uuid(4306447C-1805-438C-8B4D-DF0B8943277C),
   dual,
   nonextensible,
   helpstring("IMyPropCtrl Interface"),
   pointer_default(unique)
]
interface IMyPropCtrl : IDispatch{
};
[
   uuid(0598F03D-8712-4b44-8F7A-968EE8BF9D15),
   dual,
   nonextensible,
   helpstring("IMyDual1 Interface"),
   pointer_default(unique)
]
interface IMyDual1 : IDispatch{
};
[
   uuid(0E9220F3-5828-4882-9B5B-E5475016DBF9),
   dual,
   nonextensible,
   helpstring("IMyDual2 Interface"),
   pointer_default(unique)
]
interface IMyDual2 : IDispatch{
};

[
   object,
   uuid(B7C724E0-12E1-4F54-A627-B7753030ADC5),
   dual,
   nonextensible,
   helpstring("IMyCompositeCtrl Interface"),
   pointer_default(unique)
]
interface IMyCompositeCtrl : IDispatch{
};

[
   object,
   uuid(2AF4CB72-CC67-49CD-9C71-364A6473E19C),
   dual,
   nonextensible,
   helpstring("IThisExample Interface"),
   pointer_default(unique)
]
interface IThisExample : IDispatch{
};
[
   object,
   uuid(AC47773C-1BB7-4202-93CC-9D813C752CFF),
   dual,
   nonextensible,
   helpstring("IMyObject Interface"),
   pointer_default(unique)
]
interface IMyObject : IDispatch{
};
[
   object,
   uuid(467CD8E8-F088-4FBC-8E30-A691F3C1EA66),
   dual,
   nonextensible,
   helpstring("IOtherObject Interface"),
   pointer_default(unique)
]
interface IOtherObject : IDispatch{
};
[
   object,
   uuid(AC325F8B-4AB7-4dab-BD94-ECB5D4BF9B52),
   dual,
   nonextensible,
   helpstring("IOuterObject Interface"),
   pointer_default(unique)
]
interface IOuterObject : IDispatch{
};
[
   object,
   uuid(EF70B517-2B05-466b-9934-6BE592695061),
   dual,
   nonextensible,
   helpstring("IExample Interface"),
   pointer_default(unique)
]
interface IExample : IDispatch{
// <Snippet139>
   HRESULT SomeFunction([in] long Number, [in] BSTR String);
// </Snippet139>
};
[
   uuid(A013FAA2-8980-4f9f-A9A6-780273D6ADA3)
]
interface IExampleBase : IUnknown
{};
[
   object,
   uuid(1496C6B8-EDD8-4128-9925-A41EF8EA68DD),
   dual,
   nonextensible,
   pointer_default(unique)
]
interface IEntry2ExampleBase : IDispatch
{};
[
   object,
   uuid(27D08D9D-CC96-4885-8FDF-B6B1E42C9DBA),
   dual,
   nonextensible,
   pointer_default(unique)
]
interface IEntry2Example : IDispatch
{};
[
   uuid(687F9903-A0D5-4c82-B804-94E36B8DB0B9),
   helpstring("IAgg Interface")
]
interface IAgg : IUnknown
{
};
[
   uuid(12A375C4-6916-49c8-B8B3-C087EFD3A404),
   helpstring("IAutoAgg Interface")
]
interface IAutoAgg : IUnknown
{
};
[
   uuid(C4162AB6-BF77-425d-A9C3-5C3FC6CB196E),
   helpstring("IAutoAggB Interface")
]
interface IAutoAggB : IUnknown
{
};
[
   object,
   uuid(83EF4069-79E8-4363-891B-2C48EDBAAB4C),
   dual,
   nonextensible,
   helpstring("IMyCompositCtrl2 Interface"),
   pointer_default(unique)
]
interface IMyCompositCtrl2 : IDispatch{
};

[
   uuid(AD75E0B0-1998-49E3-8730-D3499F35B897),
   version(1.0),
   helpstring("NVC_ATL_Windowing 1.0 Type Library")
]
library NVC_ATL_WindowingLib
{
   importlib("stdole2.tlb");
   [
      uuid(83B4FF5B-AFC2-4348-8784-4CEE885FD07A),
      control,
      helpstring("MyCtrl Class")
   ]
   coclass MyCtrl
   {
      [default] interface IMyCtrl;
   };
   [
      uuid(3486029E-6E14-4B40-B99B-3556F5A3F6BD),
      control,
      helpstring("AtlEdit Class")
   ]
   coclass AtlEdit
   {
      [default] interface IAtlEdit;
   };
   [
      uuid(F73A3097-4BDE-44CD-8880-E9DD6B7AA3B9),
      control,
      helpstring("MyWindow Class")
   ]
   coclass MyWindow
   {
      [default] interface IMyWindow;
   };
   [
      uuid(C6344B07-C9C9-45C5-9EB9-B461EFE73089),
      helpstring("_IPolyCtlEvents Interface")
   ]
// <Snippet56>
   dispinterface _IPolyCtlEvents
   {
      properties:
      methods:
         [id(1), helpstring("method ClickIn")] void ClickIn([in] LONG x, [in] LONG y);
         [id(2), helpstring("method ClickOut")] void ClickOut([in] LONG x, [in] LONG y);
   };
// </Snippet56>
   [
      uuid(2CE1C12D-FD89-42C9-BE5B-2116AE21CF04),
      control,
      helpstring("PolyCtl Class")
   ]
   coclass PolyCtl
   {
      [default] interface IPolyCtl;
      [default, source] dispinterface _IPolyCtlEvents;
   };
   [
      uuid(6E57AFDA-45B0-4938-A75B-E0A4A128ADF6),
      helpstring("PolyProp Class")
   ]
   coclass PolyProp
   {
      [default] interface IUnknown;
   };
   [
      uuid(BB2A413D-70DE-44DF-8F88-9F192D019F66),
      control,
      helpstring("MyCustomWnd Class")
   ]
   coclass MyCustomWnd
   {
      [default] interface IMyCustomWnd;
   };
   [
      uuid(A79495A0-610C-4C0A-828A-589455C60E5D),
      helpstring("DatePage Class")
   ]
   coclass DatePage
   {
      [default] interface IUnknown;
   };
   [
      uuid(38723881-9E30-4BC1-81A9-6417D2524D24),
      helpstring("DocProperties Class")
   ]
   coclass DocProperties
   {
      [default] interface IUnknown;
   };
   [
      uuid(27BD7C5A-0F68-4167-8494-66809E30E57C),
      helpstring("Helper Class")
   ]
   coclass Helper
   {
      [default] interface IHelper;
   };
// <Snippet81>
   [
      uuid(3233E37D-BCC0-4871-B277-48AE6B61224A),
      helpstring("Buddy Events")
   ]
   dispinterface DBuddyEvents
   {
      properties:
      methods:
   };
// </Snippet81>
   [
      uuid(0B36CEDD-58E9-42A9-9EBD-66BFF7FB263C),
      control,
      helpstring("Buddy Class")
   ]
// <Snippet82>
   coclass Buddy
   {
      [default] interface IBuddy;
      [default,source] dispinterface DBuddyEvents;
   };
// </Snippet82>
   [
      uuid(A7034BE3-EDC3-4d11-9FAF-43846B99DB40),
      helpstring("MyEventMaker Events")
   ]
   dispinterface DMyEventMakerEvents
   {
      properties:
      methods:
         [id(1), helpstring("method MyEvent1")] void MyEvent1([in] LONG l);
   };
   [
      uuid(CD2D389F-EC55-4dcf-BA07-9597D87D13A8),
      control,
      helpstring("MyEventMaker Class")
   ]
   coclass MyEventMaker
   {
      [default,source] dispinterface DMyEventMakerEvents;
   };


//   importlib("..\..\NVC_ATL_CDispServer\Cpp\_DispServer.tlb"); //**** add this line
   [
      uuid(16D6CEFE-77A3-4914-B72A-E8D788ECDDC3),
      helpstring("MyDispEventClass Class")
   ]
   coclass MyDispEventClass
   {
      [default] interface IMyDispEventClass;
//      [default,source] dispinterface _IDispServEvents;       //**** and this one

   };
   
   [
      uuid(370498C1-09CF-47A0-9889-E02D47194996),
      helpstring("_IConnect1Events Interface")
   ]
   dispinterface _IConnect1Events
   {
      properties:
      methods:
   };
   [
      uuid(D33F7204-ECF5-423A-8905-A66A554D544D),
      helpstring("Connect1 Class")
   ]
   coclass Connect1
   {
      [default] interface IConnect1;
      [default, source] dispinterface _IConnect1Events;
   };
   [
      uuid(435750F6-2BE0-4D9C-8D46-98BFCC741AEF),
      helpstring("_IConnect2Events Interface")
   ]
   dispinterface _IConnect2Events
   {
      properties:
      methods:
   };
   [
      uuid(91152894-923E-4449-AFC8-3FB0847863BF),
      helpstring("Connect2 Class")
   ]
   coclass Connect2
   {
      [default] interface IConnect2;
      [default, source] dispinterface _IConnect2Events;
   };
   [
      uuid(33DEFD0E-104D-4B7C-B024-520C13395FF3),
      control,
      helpstring("ATLAsync Class")
   ]
   coclass ATLAsync
   {
      [default] interface IATLAsync;
   };
   [
      uuid(8C2BE9F7-AAED-442F-94CC-9BC87F7A1016),
      helpstring("MyComponent Class")
   ]
   coclass MyComponent
   {
      [default] interface IMyComponent;
   };
   [
      uuid(07B7207B-6889-41CE-BDBD-E90956F8E7D9),
      helpstring("MySink Class")
   ]
   coclass MySink
   {
      [default] interface IMySink;
   };
   [
      uuid(3A1BF4D3-1BFE-4278-8797-8D89F491DBAB),
      helpstring("CBuddySink Class")
   ]
   coclass CBuddySink
   {
      [default] interface ICBuddySink;
   };
   [
      uuid(C08767C3-3D3A-4969-804A-384A1EA32FB5),
      control,
      helpstring("MyPropCtrl Class")
   ]
   coclass MyPropCtrl
   {
      [default] interface IMyPropCtrl;
   };
   [
      uuid(2234BA36-8414-4329-9C1A-7F973E772C8E),
      helpstring("MyPropPage1 Class")
   ]
   coclass MyPropPage1
   {
      [default] interface IUnknown;
   };
   [
      uuid(E12CE950-17EB-4AB4-9198-A4B9AD05EE85),
      helpstring("MyPropPage2 Class")
   ]
   coclass MyPropPage2
   {
      [default] interface IUnknown;
      dispinterface IMyDual1;
      dispinterface IMyDual2;
   };
   [
      uuid(12BF54BC-6F6C-4585-884B-975A80107CE4),
      helpstring("MyPropPage3 Class")
   ]
   coclass MyPropPage3
   {
      [default] interface IUnknown;
   };
   [
      uuid(63367FFE-D85C-47F9-BD65-26A8B199E05C),
      control,
      helpstring("MyCompositeCtrl Class")
   ]
   coclass MyCompositeCtrl
   {
      [default] interface IMyCompositeCtrl;
   };
   [
      uuid(0A9B3801-9D4E-4D93-8BF3-39BDB2B7C651),
      helpstring("ThisExample Class")
   ]
   coclass ThisExample
   {
      [default] interface IThisExample;
   };
   [
      uuid(C8FA8EEC-B4BD-4D67-A9A8-847BC80D68EA),
      helpstring("MyObject Class")
   ]
   coclass MyObject
   {
      [default] interface IMyObject;
   };
   [
      uuid(A899763D-CC55-4D65-AFA8-A2C0FAFCC5EA),
      helpstring("OtherObject Class")
   ]
   coclass OtherObject
   {
      [default] interface IOtherObject;
   };
   [
      uuid(909D4C6D-2AA2-40de-9C6D-8CA5C674D388),
      helpstring("AutoAgg Class")
   ]
   coclass CAutoAgg
   {
      [default] interface IAutoAgg;
   };
   [
      uuid(BC44982D-EB26-4244-9A04-D60BB4ED7F4A),
      helpstring("AutoAggB Class")
   ]
   coclass CAutoAggB
   {
      [default] interface IAutoAggB;
   };
   [
      uuid(10E434B1-732F-488b-8F2A-B8A0D62EC53E)
   ]
   coclass Example
   {
      [default] interface IExampleBase;
   };
   [
      uuid(6F049E97-58FD-412f-83DA-CDCC81DE72CC)
   ]
   coclass Entry2Example
   {
      [default] interface IEntry2Example;
   };
   [
      uuid(219270F8-9F2C-46ab-9EF4-8521F9155999)   
   ]
   coclass NoAggClass
   {
      [default] interface IUnknown;
   };
   [
      uuid(FF7E0AF2-9453-479c-9263-023ED00A72D4)
   ]
   coclass MyDescribedClass
   {
      [default] interface IUnknown;
   };
   [
      uuid(F21836A1-E50D-49f9-9980-99EC03221989)
   ]
   coclass OnlyAggClass
   {
      [default] interface IUnknown;
   };
   [
      uuid(961D46DB-B1E7-444D-9EC5-AD0F5773B34B),
      control,
      helpstring("MyCompositCtrl2 Class")
   ]
   coclass MyCompositCtrl2
   {
      [default] interface IMyCompositCtrl2;
   };
};
