// NVC_MFC_AxOpt.idl : type library source for ActiveX Control project.

// This file will be processed by the MIDL compiler tool to
// produce the type library (NVC_MFC_AxOpt.tlb) that will become a resource in
// NVC_MFC_AxOpt.ocx.

#include <olectl.h>
#include <idispids.h>

[ uuid(9616D3F1-2648-44A2-90BB-373EE1233007), version(1.0),
  helpfile("NVC_MFC_AxOpt.hlp"),
  helpstring("NVC_MFC_AxOpt ActiveX Control module"),
  control ]
library NVC_MFC_AxOptLib
{
   importlib(STDOLE_TLB);

   //  Primary dispatch interface for CMyAxOptCtrl

   [ uuid(2C8C9B43-E122-4593-A6EB-163B2E8240B1),
     helpstring("Dispatch interface for MyAxOpt Control")]
   dispinterface _DNVC_MFC_AxOpt
   {
      properties:
         [id(1) , helpstring("property BoolProp")] BOOL BoolProp;
         [id(2) , helpstring("property ShortProp")] SHORT ShortProp;
         [id(3) , helpstring("property ColorProp")] OLE_COLOR ColorProp;
         [id(4) , helpstring("property StringProp")] BSTR StringProp;
   methods:
   };

   //  Event dispatch interface for CMyAxOptCtrl

   [ uuid(1C6B3943-A197-4098-88DA-917102CFD1AF),
     helpstring("Event interface for MyAxOpt Control") ]
   dispinterface _DNVC_MFC_AxOptEvents
   {
      properties:
         //  Event interface has no properties

      methods:
   };

   //  Class information for CMyAxOptCtrl

   [ uuid(8950E123-1887-4124-A4B8-06E2D7E2A164),
     helpstring("MyAxOpt Control"), control ]
   coclass NVC_MFC_AxOpt
   {
      [default] dispinterface _DNVC_MFC_AxOpt;
      [default, source] dispinterface _DNVC_MFC_AxOptEvents;
   };

};
