// NVC_MFC_AxSub.idl : type library source for ActiveX Control project.

// This file will be processed by the MIDL compiler tool to
// produce the type library (NVC_MFC_AxSub.tlb) that will become a resource in
// NVC_MFC_AxSub.ocx.

#include <olectl.h>
#include <idispids.h>

[ uuid(1BCCAD74-1AFF-4D3A-BF0C-B10339CA43C6), version(1.0),
  helpfile("NVC_MFC_AxSub.hlp"),
  helpstring("NVC_MFC_AxSub ActiveX Control module"),
  control ]
library NVC_MFC_AxSubLib
{
	importlib(STDOLE_TLB);

	//  Primary dispatch interface for CMyAxSubCtrl

	[ uuid(E1EE7929-9E40-484E-986C-B1D4812C6AAF),
	  helpstring("Dispatch interface for MyAxSub Control")]
	dispinterface _DNVC_MFC_AxSub
	{
		properties:
		methods:
	};

	//  Event dispatch interface for CMyAxSubCtrl

	[ uuid(AA4BDC29-19E1-4911-A96E-2D912C30D111),
	  helpstring("Event interface for MyAxSub Control") ]
	dispinterface _DNVC_MFC_AxSubEvents
	{
		properties:
			//  Event interface has no properties

		methods:
	};

	//  Class information for CMyAxSubCtrl

	[ uuid(6E9E4BBD-186A-45CC-96FA-5975B841CFB9),
	  helpstring("MyAxSub Control"), control ]
	coclass NVC_MFC_AxSub
	{
		[default] dispinterface _DNVC_MFC_AxSub;
		[default, source] dispinterface _DNVC_MFC_AxSubEvents;
	};

};
