//{{NO_DEPENDENCIES}}
// Microsoft Visual C++ generated include file.
// Used by NVC_MFCDocView.rc
//
#define IDD_ABOUTBOX                    100
#define IDP_OLE_INIT_FAILED             100
#define ID_INDICATOR_PAGE               101
#define IDD_COLOR                       102
#define IDS_FIRST_TOOLTIP               102
#define IDD_MYFORMVIEW                  103
#define IDS_SECOND_TOOLTIP              103
#define IDS_THIRD_TOOLTIP               104
#define IDS_PROPERTYSHEET_TITLE         105
#define IDD_MYMULTIPAGEDLG              106
#define IDR_HTML_MYMULTIPAGEDLG         107
#define IDR_MAINFRAME                   128
#define IDR_CMyDocTypeTYPE              129
#define IDR_MYTOOLBAR                   129
#define IDD_PROPPAGE1                   130
#define IDD_PROPPAGE2                   131
#define IDR_BRUSHDOCTYPE                132
#define IDB_BRUSH                       133
#define IDR_DCDOCTYPE                   133
#define IDB_BITMAP1                     137
#define IDR_RICHEDITDOCTYPE             138
#define IDR_EXAMPLEDOCTYPE              140
#define IDR_MYEDITDOCTYPE               142
#define IDR_FONTDOCTYPE                 144
#define IDD_DIALOG1                     146
#define IDD_STYLE                       147
#define IDR_SHEETDOCTYPE                147
#define IDD_SHAPE                       148
#define IDR_RGNDOCTYPE                  149
#define IDR_MYSCROLLDOCTYPE             151
#define IDR_PAGE1                       153
#define IDR_PAGE2                       154
#define IDR_PAGE3                       155
#define IDC_SLIDER1                     1003
#define IDC_EDIT1                       1004
#define IDC_EDIT2                       1005
#define IDC_SLIDER2                     1006
#define IDC_NUMOBJECTS                  1007
#define IDC_REDSLIDER                   1009
#define IDC_GREENSLIDER                 1010
#define IDC_BLUESLIDER                  1011
#define IDC_RADIOBLACK                  1013
#define IDC_RADIORED                    1014
#define IDC_RADIOBLUE                   1015
#define IDC_RADIOGREEN                  1016
#define IDC_RECTANGLE                   1017
#define IDC_ROUND_RECTANGLE             1018
#define IDC_ELLIPSE                     1019
#define ID_FILE_SWITCHVIEWS             32771
#define ID_EDIT_CLEARALL                32772
#define ID_EDIT_PROPERTIES              32773
#define ID_EDIT_WIZARD                  32774
#define ID_EDIT_IDLEPROCESSING          32775
#define ID_FILE_SENDMAIL                32776
#define ID_BRUSH_VARIETY                32777
#define ID_BRUSH_INDIRECT               32778
#define ID_BRUSH_DIBPATTERN             32779
#define ID_BRUSH_HATCH                  32780
#define ID_BRUSH_PATTERN                32781
#define ID_BRUSH_SYSCOLOR               32782
#define ID_BRUSH_LOG                    32783
#define ID_BRUSH_HANDLE                 32784
#define ID_DC_ARC                       32785
#define ID_DC_PATH                      32786
#define ID_DC_CHORD                     32787
#define ID_DC_BITMAP                    32788
#define ID_DC_3DRECT                    32789
#define ID_DC_FRAMECTL                  32790
#define ID_STUFF_ENUMPENS               32791
#define ID_DC_INVERTRECT                32792
#define ID_DC_PIE                       32793
#define ID_DC_POLYGON                   32794
#define ID_DC_RECTANGLE                 32795
#define ID_DC_RONDRECT                  32796
#define ID_STUFF_STARTDOC               32797
#define ID_DC_CLIENTDC                  32798
#define ID_CURSOR_BEGINSLEEPEND         32799
#define ID_CURSOR_BEGINDLGRESTORE       32800
#define ID_CURSOR_DLGRESTORE            32801
#define ID_CURSOR_DLGDOWAIT             32802
#define ID_SHAPE_COLOR                  32803
#define ID_SHAPE_NEWSHAPE               32804
#define ID_SHAPE_DELETESHAPE            32805
#define ID_INFO_LINENUMBER              32806
#define ID_COLORDIALOG_DOMODAL          32807
#define ID_COLORDIALOG_GETCOLOR         32808
#define ID_COLORDIALOG_GETSAVEDCUSTOMCOLORS 32809
#define ID_COLORDIALOG_M                32810
#define ID_COLORDIALOG_ONCOLOROK        32811
#define ID_DOC                          32812
#define ID_DOC_CLEARALL                 32813
#define ID_DOC_DEFAULTNAME              32814
#define ID_DOC_REPAINTALL               32815
#define ID_DOC_UPDATEALL                32816
#define ID_EDIT                         32817
#define ID_EDIT_SETLIMITTEXT            32818
#define ID_EDIT_SETTABSTOPS             32819
#define ID_INFO_FINDREPLACE             32820
#define ID_INFO_GETFRSTRING             32821
#define ID_FONT                         32822
#define ID_FONT_FONT                    32823
#define ID_FONT_FONTINDIRECT            32824
#define ID_FONT_POINTFONT               32825
#define ID_FONT_POINTFONTINDIRECT       32826
#define ID_FONT_HANDLE                  32827
#define ID_FONT_HFONT                   32828
#define ID_FONT_TRACEFONTNAME           32829
#define ID_FONTDIALOG_CFONTDIALOG       32830
#define ID_FONTDIALOG_GETCOLOR          32831
#define ID_FONTDIALOG_GETCURRENTFONT    32832
#define ID_FONTDIALOG_GETFACENAME       32833
#define ID_FONTDIALOG_GETSIZE           32834
#define ID_FONTDIALOG_GETSTYLENAME      32835
#define ID_FONTDIALOG_GETWEIGHT         32836
#define ID_FONTDIALOG_ISBOLD            32837
#define ID_FONTDIALOG_ISITALIC          32838
#define ID_FONTDIALOG_ISUNDERLINE       32839
#define ID_FONTDIALOG_M                 32840
#define ID_FONTDIALOG_ISSTRIKEOUT       32841
#define ID_FONT_CFONTDIALOG             32842
#define ID_FONTDIALOG_M32843            32843
#define ID_PSD_CTO                      32844
#define ID_PSD_DOMODAL                  32845
#define ID_PSD_MYPSD                    32846
#define ID_STUFF_CPAINTDC               32847
#define ID_STUFF_DOPENSTUFF             32848
#define ID_PRINTDLG_CREATEANDCTOR       32849
#define ID_PRINTDLG_CREATEPINTERDC      32850
#define ID_PRINTDLG_GETDEFAULTS         32851
#define ID_PRINTDLG_GETDEVICENAME       32852
#define ID_PRINTDLG_GETPRINTERDC        32853
#define ID_PRINTDLG_PRINTCOLLATE        32854
#define ID_PRINTDLG_M                   32855
#define ID_PROPPAGE_CONSTRUCT           32856
#define ID_CPROPERTYPAGE_CTOR           32857
#define ID_CPROPERTYPAGE                32858
#define ID_CPROPERTYPAGE_CONSTRUCT      32859
#define ID_CPROPERTYPAGE_CTOR32860      32860
#define ID_CPROPERTYPAGE_DOWIZARD       32861
#define ID_CPROPERTYSHEET_ADDPAGE       32862
#define ID_CPROPERTYSHEET_CONSTRUCT     32863
#define ID_CPROPERTYSHEET_CTOR          32864
#define ID_CPROPERTYSHEET_CREATE        32865
#define ID_CPROPERTYSHEET_CREATEMYPS    32866
#define ID_CPROPERTYSHEET_SETTITLE      32867
#define ID_CPROPERTYSHEET_SETWIZARDMODE 32868
#define ID_CPROPERTYSHEET_M             32869
#define ID_CPROPERTYSHEET_GETTABCONTROL 32870
#define ID_RGN                          32871
#define ID_RGN_COMBINERGN               32872
#define ID_RGN_CREATEELLIPTICRGN        32873
#define ID_RGN_CREATEPOLYGONRGN         32874
#define ID_CRGN_CREATERECTRGN           32875
#define ID_DRAW_CREATERECTRGNINDIRECT   32876
#define ID_DRAW_CREATEROUNDRECTRGN      32877
#define ID_CRGN_EQUALRGN                32878
#define ID_CRICHEDITVIEW_CHARUNDERLINE  32879
#define ID_CRICHEDITVIEW_CHARITALIC     32880
#define ID_CRICHEDITVIEW_PARACENTER     32881
#define ID_CRICHEDITVIEW_UPDATECHARITALICUI 32882
#define ID_CRICHEDITVIEW_ADDBULLETS     32883
#define ID_CRICHEDITVIEW_WORDWRAP       32884
#define ID_CRICHEDITVIEW_PRINT          32885
#define ID_CRICHEDITVIEW_REPLACE        32886
#define ID_CRICHEDITVIEW_REPLACE32887   32887
#define ID_SCROLL                       32888
#define ID_SCROLL_RECALCLAYOUT          32889
#define ID_SCROLL_SETSCROLLSIZES        32890
#define ID_VIEW_SETPANETEXT             32891
#define ID_SPIRALLYTHINGY               32892
#define ID_DHTML_MULTIPAGEDLG           32893
#define ID_EDIT_CWINDOWDC               32894
#define ID_VIEW_STARTTIMER              32895
#define ID_VIEW_KILLTIMER               32896
#define ID_AFX_AFXDRAWDITHEREDBITMAP    32897
#define ID_AFX_AFXDRAWGRAYBITMAP        32898
#define ID_AFX_AFXGETDITHEREDBITMAP     32899
#define ID_AFX_AFXGETGRAYBITMAP         32900

// Next default values for new objects
// 
#ifdef APSTUDIO_INVOKED
#ifndef APSTUDIO_READONLY_SYMBOLS
#define _APS_NEXT_RESOURCE_VALUE        156
#define _APS_NEXT_COMMAND_VALUE         32901
#define _APS_NEXT_CONTROL_VALUE         1015
#define _APS_NEXT_SYMED_VALUE           110
#endif
#endif
