// MyBound.idl : type library source for ActiveX Control project.

// This file will be processed by the MIDL compiler tool to
// produce the type library (MyBound.tlb) that will become a resource in
// MyBound.ocx.

#include <olectl.h>
#include <idispids.h>

[ uuid(F7B64DD7-8EA1-4F2F-BB56-0DDCEBBD9188), version(1.0),
  helpfile("MyBound.hlp"),
  helpstring("MyBound ActiveX Control module"),
  control ]
library MyBoundLib
{
	importlib(STDOLE_TLB);

	//  Primary dispatch interface for CMyBoundCtrl

	[ uuid(DF55EF63-8F37-474A-B1D2-4E0BF5A6CD18),
	  helpstring("Dispatch interface for MyBound Control")]
	dispinterface _DMyBound
	{
		properties:
         [id(1), helpstring("property MyBoundProp"), bindable, defaultbind, displaybind, immediatebind] BSTR MyBoundProp;
         [id(0), helpstring("property MyBoundProp"), bindable, defaultbind, displaybind, immediatebind] BSTR _MyBoundProp;
   methods:
	};

	//  Event dispatch interface for CMyBoundCtrl

	[ uuid(04948205-3968-4C52-BCCD-A470858DCE67),
	  helpstring("Event interface for MyBound Control") ]
	dispinterface _DMyBoundEvents
	{
		properties:
			//  Event interface has no properties

		methods:
	};

	//  Class information for CMyBoundCtrl

	[ uuid(4E9077D3-28F0-4943-B290-409D8FB8E35F),
	  helpstring("MyBound Control"), control ]
	coclass MyBound
	{
		[default] dispinterface _DMyBound;
		[default, source] dispinterface _DMyBoundEvents;
	};

};
