//{{NO_DEPENDENCIES}}
// Microsoft Visual C++ generated include file.
// Used by NVC_MFCWindowing.rc
//
#define IDD_ABOUTBOX                    100
#define ID_LISTBOX                      101
#define ID_CLOSEFILE                    102
#define ID_FILE_CONTEXT_HELPID          103
#define IDD_MODELESS                    104
#define IDC_TTEDIT                      105
#define HIDC_TESTHELP_CONTROL           107
#define IDR_MAINFRAME                   128
#define IDR_MYTYPE                      129
#define IDR_SPLITTYPE                   130
#define IDR_HELLO                       131
#define IDS_COLOR_NAME_FIRST            131
#define IDS_BLACK                       131
#define IDI_HELLO                       132
#define IDS_BLUE                        132
#define IDR_DRAW                        133
#define IDS_GREEN                       133
#define IDS_CYAN                        134
#define IDS_RED                         135
#define IDS_MAGENTA                     136
#define IDS_YELLOW                      137
#define IDR_SHORT_MENU                  138
#define IDS_WHITE                       138
#define IDR_MENUTYPE                    139
#define IDS_ABOUT                       139
#define IDR_MDITYPE                     141
#define IDB_CHECKBITMAP                 142
#define IDB_UNCHECKBITMAP               143
#define IDC_MYCURSOR                    144
#define IDD_MYDLG                       145
#define IDB_HAPPY_BITMAP                146
#define IDD_PENWIDTHSDLG                147
#define IDM_ABOUTBOX                    240
#define IDC_MYEDIT                      1000
#define IDC_CHECK1                      1001
#define IDC_CHECK2                      1002
#define IDC_CHECK3                      1003
#define IDC_BUTTON1                     1004
#define IDC_RADIO1                      1005
#define IDC_RADIO2                      1006
#define IDC_RADIO3                      1007
#define IDC_RADIO4                      1008
#define IDC_BUTTON2                     1009
#define IDC_BUTTON3                     1010
#define IDC_BUTTON4                     1011
#define IDC_BUTTON5                     1012
#define IDC_BUTTON6                     1013
#define IDC_BUTTON7                     1014
#define IDC_BUTTON8                     1015
#define IDC_BUTTON9                     1016
#define IDC_DIRLIST                     1017
#define IDC_DIRCOMBO                    1018
#define IDC_THINPENWIDTH                1019
#define IDC_THICKPENWIDTH               1020
#define IDC_MSACALCTRL1                 1020
#define IDC_BUTTON10                    1021
#define IDC_MYSTATIC                    1022
#define IDC_SPIN1                       1023
#define IDC_BUTTON11                    1024
#define IDC_EDITNAME                    1025
#define IDC_EDITNUM                     1026
#define IDC_BUTTON12                    1027
#define IDC_TESTHELP_CONTROL            1028
#define IDC_BUTTON14                    1029
#define ID_TEST_GETACTIVEVIEW           32771
#define ID_FILE_NEWMDICHILD             32772
#define ID_FILE_HELLO                   32773
#define ID_HELLO_CLOSE                  32774
#define ID_MDI_MAXIMIZE                 32775
#define ID_MDI_RESTORE                  32776
#define ID_FRAME_NEWDRAW                32777
#define ID_FRAME_ACTIVATEFIRSTMDICHILD  32779
#define ID_WINDOW_ARRANGE32780          32780
#define ID_WINDOW_CASCADE32781          32781
#define ID_WINDOW_TILEHORZ              32782
#define ID_WINDOW_TILEVERT              32783
#define ID_FRAME_ACTIVATENEXTWINDOW     32784
#define ID_MDI_REPLACEMENU              32785
#define ID_SHORT_I                      32786
#define ID_TEST_ACTIVATEFIRSTMDICHILD   32787
#define ID_FILE_NEW32791                32791
#define IDM_COLOR_MENU                  32794
#define ID_FRAME_SETUPCOLOR             32796
#define ID_COLOR_COLORS32797            32797
#define ID_MENU_DISABLEFILENEW          32798
#define ID_MENU_ATTACH32799             32799
#define ID_MENU_DELETETEMPMAP32800      32800
#define ID_MENU_CREATEMENU              32801
#define ID_MENU_TOGGLETEST              32802
#define ID_MENU_TOGGLEINFO              32803
#define ID_MENU_TOGGLESTATE             32804
#define ID_MENU_CHANGEFILEMENU          32805
#define ID_MENU_REPLACEMENU             32806
#define ID_MENU_LOADMENUINDIRECT        32807
#define ID_MENU_BITMAP                  32808
#define ID_WINAPP_ADDTORECENTFILELIST   32809
#define ID_WINAPP_EXITINSTANCE          32810
#define ID_WINAPP_GETPRINTERDEVICEDEFAULTS 32811
#define ID_WINAPP_WINHELP               32812
#define ID_WINAPP_GETPROFILEBINARY      32813
#define ID_WINAPP_GETPROFILEINT         32814
#define ID_WINAPP_GETPROFILESTRING      32815
#define ID_WINAPP_WRITEPROFILEBINARY    32816
#define ID_WINAPP_WRITEPROFILEINT       32817
#define ID_WINAPP_WRITEPROFILESTRING    32818
#define ID_WINAPP_M                     32819
#define ID_WINAPP_M_HINSTANCE           32820
#define ID_WINAPP_CHANGESTRINGS         32821
#define ID_CURSOR_DOCURSOR              32822
#define ID_WINAPP_APPNAME               32823
#define ID_CWND_ARRANGEICONICWINDOWS    32824
#define ID_CWND_CREATEFRAME             32825
#define ID_CWND_MYDLG                   32826
#define ID_CWND_MODELESS                32827
#define ID_CWND_FINDWINDOW              32828
#define ID_CWND_PENWIDTHSDLG            32829
#define ID_CWND_MYFILEDIALOG            32830
#define ID_CWND_DELETEFILEMENU          32831
#define ID_CWND_SHOWMODELESS            32832
#define ID_CWND_HIDEMODELESS            32833
#define ID_CWND_DISPLAYERRORMSG         32834
#define ID_HELP_ICONICABOUT             32835
#define ID_MDI_COPY                     32836
#define ID_CWND_STARTTIMER              32837
#define ID_CWND_STOPTIMER               32838
#define ID_CWND_HIDEAPP                 32839
#define ID_MDI_CHANGERECT               32840
#define ID_GLOBALS_AFXGETAPP            32841
#define ID_GLOBALS_CLOSEAPP             32842
#define ID_GLOBALS_AFXGETRESOURCEHANDLE 32843
#define ID_GLOBALS_AFXMESSAGEBOX        32844
#define ID_GLOBALS_AFXREGISTERWNDCLASS  32845

// Next default values for new objects
// 
#ifdef APSTUDIO_INVOKED
#ifndef APSTUDIO_READONLY_SYMBOLS
#define _APS_NEXT_RESOURCE_VALUE        150
#define _APS_NEXT_COMMAND_VALUE         32846
#define _APS_NEXT_CONTROL_VALUE         1030
#define _APS_NEXT_SYMED_VALUE           108
#endif
#endif
