#pragma once

template <class T>
class CProxy_INotSoSimpleEvents : public IConnectionPointImpl<T, &__uuidof( _INotSoSimpleEvents ), CComDynamicUnkArray>
{
	//Warning this class will  be regenerated by the wizard.
public:
};
