// NVC_MFC_AxUI.idl : type library source for ActiveX Control project.

// This file will be processed by the MIDL compiler tool to
// produce the type library (NVC_MFC_AxUI.tlb) that will become a resource in
// NVC_MFC_AxUI.ocx.

#include <olectl.h>
#include <idispids.h>

[ uuid(08DC9169-FAB2-45A6-94A1-AA6894FAA189), version(1.0),
  helpfile("NVC_MFC_AxUI.hlp"),
  helpstring("NVC_MFC_AxUI ActiveX Control module"),
  control ]
library NVC_MFC_AxUILib
{
   importlib(STDOLE_TLB);

   //  Primary dispatch interface for CMyAxUICtrl

   [ uuid(8FACFDF3-C2CB-4BF8-8498-21ADFA1F0113),
     helpstring("Dispatch interface for MyAxUI Control")]
   dispinterface _DNVC_MFC_AxUI
   {
      properties:
// <Snippet23>
         [id(DISPID_CAPTION), helpstring("property Caption")] BSTR Caption;
// </Snippet23>
// <Snippet26>
         [id(2), helpstring("property CircleOffset")] SHORT CircleOffset;
         [id(3), helpstring("property MyProperty")] SHORT MyProperty;
         // </Snippet26>
   methods:
// <Snippet17>
         [id(DISPID_REFRESH), helpstring("method Refresh")] void Refresh(void);
// </Snippet17>
// <Snippet19>
         [id(1), helpstring("method PtInCircle")] VARIANT_BOOL PtInCircle(OLE_XPOS_PIXELS xCoord, OLE_YPOS_PIXELS yCoord);
// </Snippet19>
         [id(4), propget, helpstring("property Array")] SHORT Array(SHORT row, SHORT column);
         [id(4), propput, helpstring("property Array")] void Array(SHORT row, SHORT column, SHORT newVal);
   };

   //  Event dispatch interface for CMyAxUICtrl

   [ uuid(9CED15D4-1A82-42AF-B131-4E16845521FE),
     helpstring("Event interface for MyAxUI Control") ]
   dispinterface _DNVC_MFC_AxUIEvents
   {
      properties:
         //  Event interface has no properties

      methods:
// <Snippet6>
         [id(DISPID_KEYPRESS)] void KeyPress(SHORT* KeyAscii);
// </Snippet6>
// <Snippet9>
         [id(1)] void ClickIn(OLE_XPOS_PIXELS xCoord, OLE_YPOS_PIXELS yCoord);
// </Snippet9>
   };

   //  Class information for CMyAxUICtrl

// <Snippet42>
   [ uuid(913E450B-E720-4C71-BCDF-71C96EE98FEB), licensed,
     helpstring("MyAxUI Control"), control ]
   coclass NVC_MFC_AxUI
// </Snippet42>
   {
      [default] dispinterface _DNVC_MFC_AxUI;
      [default, source] dispinterface _DNVC_MFC_AxUIEvents;
   };

};
